#####################
# Useful references #
#####################
# https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# https://www.fosslinux.com/80608/how-to-copy-and-paste-with-a-clipboard-in-tmux.htm

########
# Misc #
########
# General prefix
#unbind-key C-b
set-option -g prefix C-b
bind-key -N 'Send prefix' C-b send-prefix

# Keys mode
set-option -g mode-keys vi

# Reload config
bind-key -N 'Reload config' r source-file ~/.tmux.conf

set-option -g default-terminal "screen-256color"

# Prefix button remain valid up to 2s then it expires
set-option -g repeat-time 2000

# Increase scrollback buffer size from 2000 to 50000 lines
set-option -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set-option -g display-time 4000

#############
# Copy Mode #
#############
## Copy selection into system clipboard
unbind-key -T copy-mode-vi Enter
bind-key -N 'Copy to system clipboard' -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard -i'

# Copy to a file
#bind-key -N 'Copy to system clipboard' -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'cat >/tmp/clipboard'

## Begin selection mode
bind-key -N 'Begin selection' -T copy-mode-vi v send-keys -X begin-selection
## Rectangular selection 
bind-key -N 'Begin rectangular selection' -T copy-mode-vi r send-keys -X rectangle-toggle

## Override paste
unbind-key ']'

# Paste from the standard buffer
#bind-key -N 'Paste from buffer' P paste-buffer

# Paste from the system clipboard
# See: https://www.fosslinux.com/80608/how-to-copy-and-paste-with-a-clipboard-in-tmux.htm#:~:text=Copying%20and%20pasting%20data%20from,them%20into%20a%20Tmux%20session. 
bind-key -N 'Paste from buffer' P run "tmux set-buffer -b buffer0 -- \"$(xclip -selection clipboard -out)\"; tmux paste-buffer -b buffer0"

# Paste from a file
#bind-key -N 'Paste from buffer' P run "tmux set-buffer \"$(cat /tmp/clipboard)\"; tmux paste-buffer"

## Copy mode
unbind-key 'q'
bind-key -N 'Enter copy mode' q copy-mode

###########
# Session #
###########
## Rename 
unbind $
bind-key -N 'Rename current session' C-s command-prompt -I "#S" { rename-session "%%" }

###########
# Windows #
###########
## Rename 
unbind ,
bind-key -N 'Rename current window' C-w command-prompt -I "#W" { rename-window "%%" }
## Kill
unbind-key &
bind-key -N 'Kill current window' X kill-window
## Focus next
unbind-key o
unbind-key n
unbind-key p
bind-key -N 'Select next window' -r o select-window -n
## Focus previous
unbind-key O
bind-key -N 'Select previous window' -r O select-window -p

#########
# Panes #
#########
## Split horizontally
unbind-key t
unbind-key %
bind-key -N 'Split window horizontally' T split-window -h -c "#{pane_current_path}"
## Split vertically
unbind-key '"'
bind-key -N 'Split window vertically' t split-window -v -c "#{pane_current_path}"
## Kill
unbind-key ^
bind-key -N 'Kill the active pane' ^ kill-pane
## Focus right
unbind-key l
bind-key -N 'Select rigth pane' l select-pane -R
## Focus left
unbind-key h
bind-key -N 'Select left pane' h select-pane -L
## Focus up
unbind-key k
bind-key -N 'Select top pane' k select-pane -U
## Focus down
unbind-key j
bind-key -N 'Select bottom pane' j select-pane -D
## Spread out as evenly as possibly
unbind-key L
bind-key -N 'Spread panes evenly' L select-layout tiled

## Resizing
bind-key -N 'Resize pane upward'        -r C-Up     resize-pane -U 1
bind-key -N 'Resize pane downward'      -r C-Down   resize-pane -D 1
bind-key -N 'Resize pane to the left'   -r C-Left   resize-pane -L 1
bind-key -N 'Resize pane to the right'  -r C-Right  resize-pane -R 1
##############
# Status bar #
##############
set-option -g status off
set-option -g status-right ''

#########
# Mouse #
#########
## Enable mouse
set-option -g mouse on

