apiVersion: v1
clusters:
  - cluster:
      server: https://api.build01.ci.devcluster.openshift.com:6443
    name: api-build01-ci-devcluster-openshift-com
contexts:
  - context:
      cluster: api-build01-ci-devcluster-openshift-com
      namespace: ci
      user: dgemoli/api-build01-ci-devcluster-openshift-com
    name: build01
kind: Config
current-context: build01
preferences: {}
users:
  - name: dgemoli/api-build01-ci-devcluster-openshift-com
    user:
      tokenFile: /home/dgemoli/.kube/testplatform/build01-token
