apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dgemoli-ci-operator-debug
  name: boskos-config
data:
  boskos.yaml: |
    resources:
    - names:
      - aws--us-east-1--quota-slice-00
      - aws-2--us-east-1--quota-slice-00
      state: free
      type: openshift-org-aws-quota-slice
    - names:
      - aws-2-install-quota-slice-00
      - aws-2-install-quota-slice-01
      state: free
      type: openshift-org-aws--aws-2--install-quota-slice
    - names:
      - aws-install-quota-slice-00
      - aws-install-quota-slice-01
      state: free
      type: openshift-org-aws--aws--install-quota-slice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boskos
  namespace: dgemoli-ci-operator-debug
  labels:
    app: prow
    component: boskos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prow
      component: boskos
  template:
    metadata:
      labels:
        app: prow
        component: boskos
      namespace: dgemoli-ci-operator-debug
    spec:
      serviceAccountName: boskos
      terminationGracePeriodSeconds: 30
      containers:
      - name: boskos
        image: quay-proxy.ci.openshift.org/openshift/ci:ci_boskos_latest
        imagePullPolicy: Always
        args:
        - --config=/etc/config/boskos.yaml
        - --namespace=dgemoli-ci-operator-debug
        - --projected-token-file=/var/sa-token/token
        - --log-level=debug
        - --pod-name=$(POD_NAME)
        - --boskos-label-selector=app=prow,component=boskos
        - --enable-leader-election=false
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
          - containerPort: 8080
            protocol: TCP
          - name: metrics
            containerPort: 9090
            protocol: TCP
        volumeMounts:
        - name: boskos-config
          mountPath: /etc/config
          readOnly: true
        - name: service-account-token
          mountPath: /var/sa-token
      volumes:
      - name: boskos-config
        configMap:
          name: boskos-config
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: boskos-tls
  labels:
    app: prow
    component: boskos
  name: boskos
  namespace: dgemoli-ci-operator-debug
spec:
  selector:
    app: prow
    component: boskos
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: metrics
    port: 9090
    protocol: TCP
    targetPort: 9090

