#!/bin/bash

script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

grand_kubeconfig='-u'
if [[ $NO_GRAND_KUBECONFIG -eq 1 || $NO_GRAND_KUBECONFIG == "true" ]]; then
    grand_kubeconfig=''
fi

user="${CLUSTER_USER:-dgemoli}"

cat "$script_dir/cluster-list" \
    | "$script_dir/../hack/make_kubeconfigs.sh" -k "$HOME/.kube/testplatform" $grand_kubeconfig
